# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The '2' in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure('2') do |config|

  config.vm.box = 'ubuntu/bionic64'
  config.vm.network 'private_network', ip: '192.168.50.3'

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'playbook.yml'
    ansible.extra_vars = {
      ssh_password_authentication: ENV['SSH_PASSWORD_AUTHENTICATION'] || false,
      ssh_regenerate_host_keys: ENV['SSH_REGENERATE_HOST_KEYS'] || false
    }
  end
end
