---
- hosts: "{{ playbook_hosts | default('all') }}"
  serial: 1
  become: true
  tasks:
    - name: Add course SSH key to root user
      ansible.posix.authorized_key:
        user: root
        key: '{{ course_ssh_public_key }}'
        comment: comem-archidep
        state: present
