---
- hosts: all
  become: true
  gather_facts: no # See first 2 tasks.

  vars: {}
  vars_files:
    - ../data.yml

  tasks:

    # Make sure python 2 is installed before doing anything
    # (this is not the case by default on Ubuntu Bionic).
    - name: Install Python
      raw: command -v python3 && command -v pip3 || { apt-get update && apt-get install -y python3 python3-apt python3-pip; }
      changed_when: false
      tags: [ always ]

    # Gather ansible facts (requires python).
    # Facts are required for many Ansible modules to work correctly.
    - name: Gather facts
      setup:
      tags: [ always ]

    - name: Upgrade all packages
      apt:
        name: "*"
        autoremove: true
        force_apt_get: true
        state: latest
      register: upgrade_packages
      tags: [ setup, upgrade ]

    - name: Set hostname
      hostname:
        name: "{{ student_username | replace('_', '-') }}.{{ base_domain }}"
      tags: [ setup ]

    - name: Enable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication '
        line: 'PasswordAuthentication yes'
      register: enable_ssh_password_authentication
      tags: [ ssh, setup ]

    - name: Restart SSH server
      service:
        name: ssh
        state: restarted
      when: enable_ssh_password_authentication is changed
      tags: [ ssh, setup ]

    - name: Create student user
      user:
        name: "{{ student_username }}"
        password: "{{ student_hashed_password }}"
        groups: "{{ [ 'sudo' ] if sudo is defined and sudo else None }}"
        shell: /bin/bash
      tags: [ setup ]

    - name: Create alice user
      user:
        name: alice
        password: "{{ alice_hashed_password }}"
        shell: /bin/bash
      tags: [ setup ]

    - name: Ensure permissions of alice's home directory
      file:
        path: /home/alice
        mode: 0750
        state: directory
      tags: [ setup ]

    - name: Reboot
      reboot:
      when: (reboot is defined and reboot) or (upgrade_packages is defined and upgrade_packages is changed)
      tags: [ reboot, setup, upgrade ]
